default_stages: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: requirements-txt-fixer
        stages: [pre-commit]
      - id: check-added-large-files
        stages: [pre-commit]
        args: ["--maxkb=50000"]
      - id: check-case-conflict
        stages: [pre-commit]
      - id: mixed-line-ending
        stages: [pre-commit]
      - id: no-commit-to-branch
        args: [--branch=main]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-check
        args: [--select, "I,RUF022", --fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.18.2"
    hooks:
      - id: mypy
        stages: [pre-commit]
        language: system
        pass_filenames: false
        args: [-p, pytximport]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        stages: [pre-commit]
        args: [--verbose, --ini, .bandit.ini, -ll, --recursive, pytximport]
  - repo: local
    hooks:
      - id: unittests
        stages: [pre-commit]
        name: unittests
        entry: uv run coverage run -m pytest --maxfail=10
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
